name: Reusable workflow Demo
on: 
  workflow_call:
    inputs:
      artifacts-name:
        description: The name of deployable artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get caode
        uses: actions/download-artifacts@v5
        with:
          name: ${{ inputs.artifacts-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying and uploading...."
