name: Reusable workflow Demo
on: 
  workflow_call:
    inputs:
      artifacts-name:
        description: The name of deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: getting outputs
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get caode
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifacts-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying and uploading...."
      - name: set output result
        id: set-result
        run: echo "step-result=success" $GITHUB_OUTPUT
